### ISSUE TITLE
mockhttp.Entry.collect can't really handle more than one request properly

### ISSUE THREAD

**Issue by glandium** [mocketize/python-mocket#14]
mockhttp.Entry.collect does this:
    self._sent_data += data
    return super(Entry, self).collect(self._sent_data)

which means that apart from the first request, all subsequent requests are actually going to be using the first request headers, and the other requests as body data.

**Comment by mindflayer** [comment]
I think it should be fixed as well with my last merge.

**Comment by ajhodges** [comment]
This is still an issue;  the same 'entry' is reused for requests to the same host/port. mockhttp.Entry tracks _sent_data, and each request appends to _sent_data. but the entire _sent_data is sent to super.collect(), which is where it's passed into the Request class, and everything but the first _sent_data is truncated when the data is parsed.

**Comment by mindflayer** [comment]
Hi @ajhodges, do you have a specificfailing  test case for the problem you are referring to?

**Comment by ajhodges** [comment]
Sure - I've added a failing test case here:
https://github.com/ajhodges/python-mocket/commit/cbae40c5ab2821dcc38c6dcfbf8d91b6edb1322d

Both of these assertions are currently failing. Somehow there are 3 requests getting added when only two are made, and they all have the same data as the first request (the one with the query params)

**Comment by mindflayer** [comment]
Hi @ajhodges, I am working at a fix. The problem that makes your test fail has nothing to do with multiple requests.
It's a bug in managing the second `sendall` sent by `requests` when sending the JSON body. I am on it.

**Comment by mindflayer** [comment]
Just for clarifying: the fact that the same `Entry` is re-used is a `mocket` feature and it has been like that since the very beginning. The APIs have been consistent since we released it in 2013. If you need different responses for the same path you explicitly create two different `entries`.

**_In case you feel you have a problem which is similar to this please open a new issue, and add a snippet which shows your problem._**
